create schema CCFRP;

-- Creating the CCFRP tablesdrift_info_all
create table CCFRP.drift_info_all (
	drift_id varchar(16),
	trip_id varchar(16),
	id_cell_per_trip varchar(1),
	grid_cell_id varchar(4),
	site varchar(4),
	drift_hold_station varchar(1),
	start_time varchar(16),
	end_time varchar(16),
	drift_time_hrs varchar(1),
	bar_fishing_time int4,
	fly_fishing_time int4,
	bat_fishing_time int4,
	dpr_fishing_time int4,
	sbt_fishing_time int4,
	total_time_hrs varchar(1),
	number_bat_fishers int4,
	number_fly_fishers int4,
	number_dpr_fishers int4,
	number_sbt_fishers int4,
	number_bar_fishers int4,
	total_anglers_fishing int4,
	total_angler_hrs varchar(1),
	st_latdd float4,
	st_londd float4,
	start_gps_waypoint int4,
	start_waypoint_link varchar(1),
	end_latdd float4,
	end_londd float4,
	end_gps_waypoint int4,
	end_gps_waypoint_link varchar(1),
	drift_length_m varchar(1),
	recorder varchar(4),
	tag_crew varchar(4),
	surface_t varchar(1),
	depth_t varchar(1),
	swt_vessel_f int4,
	relief int4,
	start_depth_ft int4,
	end_depth_ft int4,
	lingcod_bar_weight_oz int4,
	lead_weight_oz int4,
	sbt_tail_length_in int4,
	sbt_head_weight_oz int4,
	number_seals int4,
	number_sea_lions int4,
	total_fishes_caught int4,
	cloud_cover int4,
	wind_speed_kt varchar(4),
	wind_direction varchar(4),
	swell_height_ft int4,
	secchi_depth_m varchar(1),
	trip_comments varchar(128),
	excluded_drift_comments varchar(1),
	exclude_gear_specific_cpue varchar(1) 
);

create table CCFRP.hk_drift_info (
	drift_id varchar(16),
	trip_id varchar(8),
	id_cell_per_trip varchar(1),
	grid_cell_id varchar(4),
	site varchar(4),
	drift_hold_station varchar(1),
	start_time varchar(16),
	end_time varchar(16),
	drift_time_hrs varchar(1),
	bar_fishing_time int4,
	fly_fishing_time int4,
	bat_fishing_time int4,
	dpr_fishing_time int4,
	sbt_fishing_time int4,
	total_time_hrs varchar(1),
	number_bat_fishers int4,
	number_fly_fishers int4,
	number_dpr_fishers int4,
	number_sbt_fishers int4,
	number_bar_fishers int4,
	total_anglers_fishing int4,
	total_angler_hrs varchar(1),
	st_latdd float4,
	st_londd float4,
	start_gps_waypoint int4,
	start_waypoint_link varchar(1),
	end_latdd float4,
	end_londd float4,
	end_gps_waypoint int4,
	end_gps_waypoint_link varchar(1),
	drift_length_m varchar(1),
	recorder varchar(4),
	tag_crew varchar(4),
	surface_t varchar(1),
	depth_t varchar(1),
	swt_vessel_f float4,
	relief int4,
	start_depth_ft int4,
	end_depth_ft int4,
	lingcod_bar_weight_oz int4,
	lead_weight_oz int4,
	sbt_tail_length_in int4,
	sbt_head_weight_oz int4,
	number_seals int4,
	number_sea_lions int4,
	total_fishes_caught int4,
	cloud_cover int4,
	wind_speed_kt varchar(4),
	wind_direction varchar(4),
	swell_height_ft int4,
	secchi_depth_m varchar(1),
	trip_comments varchar(32),
	excluded_drift_comments varchar(1),
	exclude_gear_specific_cpue varchar(1) 
);

create table CCFRP.hk_fishes (
	fish_id varchar(1),
	drift_id varchar(16),
	species_code varchar(4),
	tag_id varchar(8),
	length_cm int4,
	gear_type varchar(4),
	station_number int4,
	angler_id varchar(4),
	depth_released_ft int4,
	lat_released_dd varchar(1),
	lon_released_dd varchar(1),
	sex varchar(1),
	condtion_0 int4,
	condtion_1 int4,
	condtion_2 int4,
	condtion_3 int4,
	condtion_4 int4,
	condtion_5 int4,
	condtion_6 int4,
	condtion_7 int4,
	condtion_8 int4,
	all_conditions varchar(1),
	retained int4,
	recapture int4,
	trip_comments varchar(32),
	gps_waypoint int4,
	waypoint_link varchar(1) 
);

create table CCFRP.Reference_Barcodes (
	phylum varchar(8),
	class varchar(16),
	sp_order varchar(32),
	family varchar(32),
	genus varchar(32),
	species varchar(32),
	binomial varchar(32),
	sequence varchar(256)
);

create table CCFRP.ccfrp_species_codes (
	species_code varchar(4),
	common_name varchar(64),
	genus varchar(16),
	species varchar(32),
	rockfish bool
);

create table CCFRP.sequenced_data(
	sequence varchar(256),
	rel_abun_total int4,
	rel_abun_fish int4,
	CONSTRAINT sequenced_data_pkey PRIMARY KEY (sequence)
);

create table CCFRP.waypoints (
	Date varchar(16),
	text_date int4,
	Time varchar(16),
	gps_waypoint int4,
	waypoint_link varchar(16),
	lat_dd float4,
	lon_dd float4,
	gps_num int4,
	name int4,
	wp_id varchar(16)
);

create table CCFRP.ccfrp_2020_edna (
	ID varchar(15),
    Project varchar(10),
    collection_date date,
	cell_location varchar(16),
	replicate varchar(4),
	collection_site varchar(16),
	cell_type varchar(16),
	collector varchar(8),
	vessel varchar(16),
	site_start time,
	site_end time,
	conditions varchar(1),
	sst_f float(3,1),
	rugosity int4,
	site_depth_ft float4,
	filter_type varchar(16),
	filter_pore_um float(3,2),
	niskin_closed varchar(8),
	lat float(8,6),
	lon float(9,6),
	filtration_date date,
	filtration_time time,
	filterer varchar(8),
	filtration_site varchar(16),
	turbidity float(3,2),
	ph float(3,2),
	vol_l float4,
	appr_niskin_line_out int4,
	niskin_depth_probe float(15,13),
	temp_at_depth float(4,2),
	notes varchar(256),
	ann_labels varchar(16),
	edna_sample_status int(1),
    extraction_date date,
    SU_Serial int4
);

create table CCFRP.ccfrp_2021_edna (
	ID varchar(15),
    project varchar(10),
    collection_date date,
	cell_location varchar(32),
	replicate varchar(4),
	collection_site varchar(2),
	cell_type varchar(4),
	collectors varchar(8),
	vessel varchar(16),
	site_start time,
	site_end time,
	niskin_closed time,
	waypoint int4,
	lat float(8,6),
	lon float(9,6),
	conditions varchar(256),
	sst_f float(3,1),
	rugosity int4,
	site_depth_ft int4,
	appr_niskin_line_out int4,
	niskin_depth_probe float(15,13),
	temp_at_depth float(4,2),
	filter_type varchar(8),
	filter_pore_um float(3,2),
	filtration_date date,
	filtration_time time,
	filterer varchar(8),
	filtration_site varchar(32),
	turbidity float(3,2),
	ph float(3,2),
	vol_l float(3,2),
	notes varchar(128),
    edna_sample_status int(1),
	extracted date,
    SU_Serial int4
);

create table CCFRP.caught_fishes_all (
	fish_id varchar(1),
	drift_id varchar(16),
	species_code varchar(4),
	tag_id varchar(8),
	length_cm int4,
	gear_type varchar(4),
	station_number int4,
	angler_id varchar(4),
	depth_released_ft int4,
	lat_released_dd varchar(1),
	lon_released_dd varchar(1),
	sex varchar(1),
	condtion_0 int4,
	condtion_1 int4,
	condtion_2 int4,
	condtion_3 int4,
	condtion_4 int4,
	condtion_5 int4,
	condtion_6 int4,
	condtion_7 int4,
	condtion_8 int4,
	all_conditions varchar(1),
	retained int4,
	recapture int4,
	trip_comments varchar(64),
	gps_waypoint int4,
	waypoint_link varchar(1)
);

create table CCFRP.ccfrp_2020_sequencing (
	`date` varchar(8),
	location varchar(256),
	replicate varchar(256),
	region varchar(256),
	type varchar(256),
	miseq_run_date varchar(256),
	sample_name_miseq_run varchar(256),
	number_of_read varchar(256)
);

-- drop table if exists CCFRP.Reference_Barcodes cascade; 
-- drop table if exists CCFRP.sequenced_data cascade; 
-- drop table if exists CCFRP.waypoints cascade;
-- drop table if exists CCFRP.ccfrp_2020_edna cascade;
-- drop table if exists CCFRP.ccfrp_2021_edna cascade;
-- drop table if exists CCFRP.Caught_fishes_all cascade;
-- drop table if exists CCCFRP.CFRP_2020_Sequencing cascade;
-- drop table if exists CCFRP.drift_info_all cascade;
-- drop table if exists CCFRP.hk_drift_info cascade;
-- drop table if exists CCFRP.hk_fishes cascade;